apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: eda-operator
  namespace: eda
resources:
  - config/default

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/eda-server-operator
    newTag: 1.0.2

# Specify a custom namespace in which to install EDA
namespace: eda