apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redis-enterprise-operator-cert
  namespace: openshift-operators
spec:
  targetNamespaces: 
    - tfe
  channel: production
  name: redis-enterprise-operator-cert
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redis-enterprise-operator.v7.4.6-2.0
  installPlanApproval: Automatic