apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: tferedisclus
  namespace: tfe
spec:
  bootstrapperImageSpec:
    repository: registry.connect.redhat.com/redislabs/redis-enterprise-operator
  persistentSpec:
    enabled: true
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    repository: registry.connect.redhat.com/redislabs/redis-enterprise
  redisEnterpriseServicesRiggerImageSpec:
    repository: registry.connect.redhat.com/redislabs/services-manager
  nodes: 3
  uiServiceType: ClusterIP
