kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: custom-scc
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000730000
  uidRangeMax: 1000739999
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    level: "s0:c27,c14"
